# Generated by Django 5.2 on 2025-06-26 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_user_alter_article_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 26, 19, 10, 16, 911697)),
        ),
    ]
