# Generated by Django 5.2 on 2025-06-23 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 23, 18, 45, 59, 911443)),
        ),
    ]
